name: macOS checks
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Core checks
        run: ./Scripts/test.sh
      - name: Build application
        run: ./Scripts/build.sh
